### ISSUE TITLE
No payouts to wallet

### ISSUE THREAD

**Issue by pav-hash** [VeriBlock/pop-phl#22]
I am not seeing any balance in the payout address wallet.

I am attaching a quick log of the pop miner displaying submits, and 1 warning that I get from time to time.
[no_payout_logfile.txt](https://github.com/VeriBlock/pop-phl/files/5696553/no_payout_logfile.txt)

**Comment by Warchant** [comment]
@pav-hash please use `validateaddress` on address, and use `scriptPubKey` instead of phl address in `application.conf`. In new updates this procedure will become automatic.

**Comment by pav-hash** [comment]
I have tried both a regular phl payout address and also the scriptPubKey address.. same result (no payouts) on either.
I have given both address a few hours each to see if either works.

**Comment by Warchant** [comment]
Was fixed in #25
